In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_data = pd.read_csv('train.csv')

In [3]:
test_data = pd.read_csv('test.csv')
sample_submission = pd.read_csv('sample_submission.csv')

In [4]:
train_data.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [5]:
train_data.shape

(630000, 13)

In [6]:
y = train_data.exam_score

In [7]:
 x = train_data.drop(['id', 'exam_score'], axis=1)

In [8]:
x.shape

(630000, 11)

In [9]:
x_test = test_data.drop(['id'], axis=1)

In [10]:
x = pd.get_dummies(x, drop_first=True, dtype=int)
x_test = pd.get_dummies(x_test, drop_first=True, dtype=int)

In [11]:
x

,age,study_hours,class_attendance,sleep_hours,gender_male,gender_other,course_b.sc,course_b.tech,course_ba,course_bba,...,sleep_quality_good,sleep_quality_poor,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,facility_rating_low,facility_rating_medium,exam_difficulty_hard,exam_difficulty_moderate
0,21,7.91,98.8,4.9,0,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
1,18,4.95,94.8,4.7,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
2,20,4.68,92.6,5.8,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,19,2.00,49.5,8.3,1,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,23,7.65,86.9,9.6,1,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,4.86,70.7,4.1,0,0,0,1,0,0,...,1,0,0,1,0,0,0,0,0,1
629996,21,7.08,54.4,4.5,0,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,1
629997,24,0.64,44.2,4.3,1,0,0,0,0,0,...,0,1,0,0,1,0,1,0,0,1
629998,20,1.54,75.1,8.2,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
629999,18,3.94,75.3,5.8,0,1,0,1,0,0,...,0,1,0,0,1,0,1,0,0,0

In [12]:
x, x_test = x.align(x_test, join='left', axis=1, fill_value=0)

In [13]:
x.shape

(630000, 23)

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
rf_model = RandomForestRegressor(random_state=0)

In [16]:
rf_model.fit(x, y)

RandomForestRegressor(random_state=0)

In [23]:
for feature, importance in zip(x.columns, rf_model.feature_importances_):
    print(f"{feature}: {importance:.4f}")

age: 0.0244
study_hours: 0.6299
class_attendance: 0.1401
sleep_hours: 0.0543
gender_male: 0.0059
gender_other: 0.0059
course_b.sc: 0.0052
course_b.tech: 0.0054
course_ba: 0.0041
course_bba: 0.0046
course_bca: 0.0049
course_diploma: 0.0037
internet_access_yes: 0.0035
sleep_quality_good: 0.0142
sleep_quality_poor: 0.0244
study_method_group study: 0.0084
study_method_mixed: 0.0057
study_method_online videos: 0.0089
study_method_self-study: 0.0100
facility_rating_low: 0.0192
facility_rating_medium: 0.0070
exam_difficulty_hard: 0.0045
exam_difficulty_moderate: 0.0062

In [18]:
importances = rf_model.feature_importances_

In [24]:
x = train_data[['study_hours', 'class_attendance', 'sleep_hours']]

In [25]:
x_test = test_data[['study_hours', 'class_attendance', 'sleep_hours']]

In [26]:
rf_model.fit(x, y)

RandomForestRegressor(random_state=0)

In [27]:
pred = rf_model.predict(x_test)

In [29]:
test = pd.read_csv('test.csv')

In [30]:
submission = pd.DataFrame({'id' : test['id'], 'exam_score': pred})

In [31]:
submission

            id  exam_score
0       630000    71.36500
1       630001    72.99000
2       630002    81.04200
3       630003    50.08200
4       630004    51.62800
...        ...         ...
269995  899995    59.73225
269996  899996    40.99350
269997  899997    75.49600
269998  899998    62.89700
269999  899999    71.68250

[270000 rows x 2 columns]

In [32]:
submission.to_csv('submission.csv', index=False)